name: Build & Release

on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust_target: x86_64-unknown-linux-gnu
            artifact_name: binary-bin-linux-amd64
          - rust_target: aarch64-unknown-linux-gnu
            artifact_name: binary-bin-linux-arm64
          - rust_target: x86_64-apple-darwin
            artifact_name: binary-bin-macos-amd64
          - rust_target: aarch64-apple-darwin
            artifact_name: binary-bin-macos-arm64
          - rust_target: x86_64-pc-windows-gnu
            artifact_name: binary-bin-windows-amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove Env
        uses: JesseTG/rm@v1.0.3
        with:
          path: .env

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.rust_target }}

      - name: Install Mingw for Windows cross-compilation
        if: matrix.rust_target == 'x86_64-pc-windows-gnu'
        run: sudo apt-get install -y gcc-mingw-w64-x86-64

      - name: Build the binary
        run: |
          cargo build - release - target ${{ matrix.rust_target }}
          if [[ "${{ matrix.artifact_name }}" == *.exe ]]; then
            mv target/${{ matrix.rust_target }}/release/app_name.exe ${{ matrix.artifact_name }}
          else
            mv target/${{ matrix.rust_target }}/release/app ${{ matrix.artifact_name }}
          fi
